-- ============================================================
-- FreePass Data Migration — Generated from Adalo CSV exports
-- Generated: 2026-05-21T19:15:13.699Z
-- Run in: Supabase Dashboard > SQL Editor > New Query
-- ============================================================

BEGIN;

-- Create missing tables if they do not exist

CREATE TABLE IF NOT EXISTS public.courses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  course_type text,
  web_link text,
  video_link text,
  in_learning_academy boolean DEFAULT false,
  is_hidden boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  display_order int,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.course_tasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  course_id uuid REFERENCES public.courses(id) ON DELETE CASCADE NOT NULL,
  name text NOT NULL,
  description text,
  sort_order float,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.questions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  question text NOT NULL,
  category text,
  upvotes int DEFAULT 0,
  is_faq boolean DEFAULT false,
  asked_by text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.answers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  question_id uuid REFERENCES public.questions(id) ON DELETE CASCADE NOT NULL,
  answer text NOT NULL,
  answered_by text,
  upvotes int DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.answers ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='courses' AND policyname='Anyone can view courses') THEN
    CREATE POLICY "Anyone can view courses" ON public.courses FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='course_tasks' AND policyname='Anyone can view course tasks') THEN
    CREATE POLICY "Anyone can view course tasks" ON public.course_tasks FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='questions' AND policyname='Anyone can view questions') THEN
    CREATE POLICY "Anyone can view questions" ON public.questions FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='questions' AND policyname='Authenticated users can ask questions') THEN
    CREATE POLICY "Authenticated users can ask questions" ON public.questions FOR INSERT TO authenticated WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='answers' AND policyname='Anyone can view answers') THEN
    CREATE POLICY "Anyone can view answers" ON public.answers FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='answers' AND policyname='Authenticated users can answer') THEN
    CREATE POLICY "Authenticated users can answer" ON public.answers FOR INSERT TO authenticated WITH CHECK (true);
  END IF;
END $$;

-- Create remaining tables if they don't exist
CREATE TABLE IF NOT EXISTS public.events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  location text,
  address text,
  event_date timestamptz NOT NULL,
  end_date timestamptz,
  instructor text,
  is_published boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.resource_categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  icon text,
  sort_order int DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.resources (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category_id uuid,
  name text NOT NULL,
  description text,
  address text,
  city text DEFAULT 'Philadelphia',
  state text DEFAULT 'PA',
  zip_code text,
  phone text,
  email text,
  website text,
  hours text,
  latitude double precision,
  longitude double precision,
  is_published boolean DEFAULT true,
  tags text[] DEFAULT '{}',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.saved_resources (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  resource_id uuid NOT NULL,
  created_at timestamptz DEFAULT now(),
  UNIQUE(user_id, resource_id)
);

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='events' AND policyname='Anyone can view published events') THEN
    CREATE POLICY "Anyone can view published events" ON public.events FOR SELECT USING (is_published = true);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_course_tasks_course_id ON public.course_tasks(course_id);
CREATE INDEX IF NOT EXISTS idx_answers_question_id ON public.answers(question_id);
CREATE INDEX IF NOT EXISTS idx_events_is_published_date ON public.events(is_published, event_date) WHERE is_published = true;

-- Clear existing data (order matters for FK constraints)
DELETE FROM public.answers;
DELETE FROM public.questions;
DELETE FROM public.course_tasks;
DELETE FROM public.courses;
DELETE FROM public.saved_resources;
DELETE FROM public.resources;
DELETE FROM public.resource_categories;
DELETE FROM public.events;

-- Resource Categories (21 rows)
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Education', 1);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Life Skills', 2);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Mental Health', 3);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Clothing Assistance', 4);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Low Income', 5);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Homelessness', 6);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Young Adults', 7);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Women', 8);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Benefits', 9);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Support Services', 10);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Insurance', 11);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Caretaking', 12);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Disability', 13);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Community Support', 14);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Legal Services', 15);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Wellness', 16);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Food', 17);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Technology', 18);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Other', 19);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Employment', 20);
INSERT INTO public.resource_categories (name, sort_order) VALUES ('Housing', 21);

-- Resources (103 non-draft rows)
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('The Fountain Fund', 'We provide low-interest loans and financial coaching to formerly incarcerated people, helping them build credit and achieve their self-determined goals. The Fountain Fund also advocates for public policy that increases economic opportunities and reduces obstacles for formerly incarcerated people.', '245 N Broad St suite 300, Philadelphia, PA 19107, USA', 'Philadelphia', 'PA', '19107', '(267) 209-0042', 'mbutler@fountainfund.org', 'www.fountainfund.org', 'Monday - Friday (9AM to 5PM)', 39.95710372163185, -75.16240371416484, TRUE, ARRAY['Financial Education', 'Access to Capital', 'Benefits']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Broad Street Love', 'Open, safe space offering stabilizing services to Philadelphia''s most vulnerable. Rooted in dignity, care & radical hospitality.', '315 S Broad St, Philadelphia, PA 19107, USA', 'Philadelphia', 'PA', '19107', '(215) 735-4847', 'info@broadstreetlove.org', 'broadstreetlove.org', 'Monday - Friday (11:30 AM – 3 PM)
Saturday/Sunday (CLOSED)', 39.94613588960327, -75.1647525094843, TRUE, ARRAY['Support Services', 'Housing', 'Employment']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Triple Bottom Brewery', 'Philadelphia craft brewery with triple bottom line: beer, people, planet. Fair chance employer brewing balanced, flavorful beers.', '915 Spring Garden St, Philadelphia, PA 19123, USA', 'Philadelphia', 'PA', '19123', '(267) 764-1994', 'hello@triplebottombrewing.com', 'https://triplebottombrewing.com/', 'Wednesday - Friday (3PM -- 10PM)
Saturday (12–10 PM)
Sunday (12–7 PM)
Monday/Tuesday (CLOSED)', 39.9618018856345, -75.15360213934774, TRUE, ARRAY['Food', 'Other', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Down North Pizza', 'Simple counter-service eatery featuring pizza, chicken wings & fries, plus milkshakes.', '2804 W Lehigh Ave, Philadelphia, PA 19132, USA', 'Philadelphia', 'PA', '19132', '(215) 377-9787', NULL, 'downnorthpizza.com', 'Thursday (12PM–9 PM)
Friday/Saturday (12PM – 10PM)
Sunday (12PM–8 PM)
Monday - Wednesday (CLOSED)', 39.99676652311965, -75.17717358434102, TRUE, ARRAY['Food', 'Other', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('The Center for Employment Opportunities', 'Philadelphia-based organization providing immediate, comprehensive employment support exclusively to formerly incarcerated.', '245 N Broad St suite 300, Philadelphia, PA 19107, USA', 'Philadelphia', 'PA', '19107', '(215) 309 7220', 'CEOPhiladelphia@ceoworks.org', 'https://www.ceoworks.org/philadelphia', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 39.95710372163185, -75.16240371416484, TRUE, ARRAY['Employment', 'Support Services', 'Life Skills']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Pathways to Housing PA', 'We provide stable housing, supportive services, and a caring community.', '5201 Old York Rd 4th floor, Philadelphia, PA 19141, USA', 'Philadelphia', 'PA', '19141', '(215) 390-1500', NULL, 'https://pathwaystohousingpa.org/', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 40.03239932556499, -75.14507493117233, TRUE, ARRAY['Housing', 'Other', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Ready, Willing & Able', 'Addressing substance use disorder through transitional housing, case management, job training & community cleanup in Philadelphia.', '1221 Bainbridge St, Philadelphia, PA 19147, USA', 'Philadelphia', 'PA', '19147', '(215) 795-3255', NULL, 'https://www.rwaphila.org/', NULL, 39.94248895704966, -75.16278209232043, TRUE, ARRAY['Support Services', 'Other', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Impact Services Corporation', 'We are a community action organization mobilizing people and resources to create connected, resilient, thriving communities.', '1952 E Allegheny Ave, Philadelphia, PA 19134, USA', 'Philadelphia', 'PA', '19134', '(215) 739-1600', 'info@impactservices.org', 'https://www.impactservices.org/', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 39.99433439522044, -75.1116852334961, TRUE, ARRAY['Support Services', 'Other', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Cordelia Homes', 'Cordelia Homes assists with various reasources, please look below for more information', '1515 Fairmount Ave, Philadelphia, PA 19130, USA', 'Philadelphia', 'PA', '19130', '(856) 477-3277', 'simplehomesfullercenter@gmail.com', 'http://www.simplehomes.org/about-us', NULL, 39.9671328, -75.1629963, TRUE, ARRAY['Housing', 'Wellness', 'Support Services']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Station House Transitional Shelter', 'Low-income housing provider offering subsidized SRO and 1-bedroom units. Contact management for details.', '2601 N Broad St, Philadelphia, PA 19132, USA', 'Philadelphia', 'PA', '19132', '(215) 225-9230', 'stationhouse@ingerman.com', 'https://reentry.networkofcare.org/philadelphia-pa/services/agency?pid=stationhouseapartments_1147_12_0', 'OPEN 24/7', 39.99222618704379, -75.15469931895339, TRUE, ARRAY['Support Services', 'Housing', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Bethesda Project – Our Brother''s Place', 'Philadelphia nonprofit providing shelter, housing & community support at 11 locations for homeless adults to stabilize & rebuild.', '907 Hamilton St, Philadelphia, PA 19123, USA', 'Philadelphia', 'PA', '19146', '(215) 985-1600', 'communitylife@bethesdaproject.org', 'https://www.bethesdaproject.org/', 'OPEN 24/7', 39.960202196333896, -75.15385086327814, TRUE, ARRAY['Housing', 'Support Services', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Bethesda Project – My Brother''s House', 'Philadelphia nonprofit providing shelter, housing & community support at 11 locations for homeless adults to stabilize & rebuild.', '609 S 15th St, Philadelphia, PA 19146, USA', 'Philadelphia', 'PA', '19146', '(215) 985-1600', 'communitylife@bethesdaproject.org', 'https://www.bethesdaproject.org/', 'OPEN 24/7', 39.943579106213605, -75.16718313489362, TRUE, ARRAY['Housing', 'Support Services', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Bethesda Project Office', 'Philadelphia nonprofit providing shelter, housing & community support at 11 locations for homeless adults to stabilize & rebuild.', '1630 South St, Philadelphia, PA 19146, USA', 'Philadelphia', 'PA', '19146', '(215) 985-1600', 'communitylife@bethesdaproject.org', 'https://www.bethesdaproject.org/our-locations', NULL, 39.94412507745815, -75.16981623125758, TRUE, ARRAY['Housing', 'Support Services', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Philly House', 'For over 145 years, Philly House has served as Philadelphia''s sanctuary, empowering those in need of food, shelter & hope.', '302 N 13th St, Philadelphia, PA 19107, USA', 'Philadelphia', 'PA', '19107', '(215) 922-6400', 'info@phillyhouse.org', 'https://www.phillyhouse.org/', 'OPEN 24/7', 39.958032618478384, -75.16027974895924, TRUE, ARRAY['Shelter', 'Support Services', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('North Philadelphia Municipal Services Center', 'One-stop service center for water bills, tax accounts, payment assistance & more. Located at 2761 N. 22nd St, Philadelphia.', '2761 N 22nd St, Philadelphia, PA 19132, USA', 'Philadelphia', 'PA', '19132', '(267) 271-4973', 'revenue@phila.gov', 'https://www.phila.gov/departments/department-of-revenue/about/contact-us/', 'Monday - Thursday (8:30AM – 5PM)', 39.997023305747845, -75.16714083951064, TRUE, ARRAY['Support Services', 'Other', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Esperanza Health Center', 'Esperanza Health Center provides holistic healthcare as a multi-cultural ministry serving Latino & underserved Philadelphians.', '4417 N 6th St, Philadelphia, PA 19140, USA', 'Philadelphia', 'PA', '19140', '(215) 302-3600', NULL, 'https://esperanzahealth.com/', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 40.01906715995974, -75.1366876847415, TRUE, ARRAY['Healthcare', 'Support Services', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('United Communities Southeast Philadelphia Houston Center', 'Since 1847, serving Southeast Philadelphia families with after-school programs, adult education, housing counseling & emergency assistance.', '2029 S 8th St, Philadelphia, PA 19148, USA', 'Philadelphia', 'PA', '19148', '(215) 468-1645', NULL, 'https://www.idealist.org/en/nonprofit/8ec967532fce45ffb72e106ee97f211c-united-communities-southeast-philadelphia-philadelphia', 'Monday - Thursday (10AM - 3PM)
Friday - Sunday (CLOSED)', 39.923224357510435, -75.15960224025156, TRUE, ARRAY['Education', 'Housing', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Philadelphia FIGHT', 'Comprehensive health services organization providing primary medical & dental care, consumer education, advocacy & research.', '1207 Chestnut St 3rd floor, Philadelphia, PA 19107, USA', 'Philadelphia', 'PA', '19107', '(215) 525-8636', 'fight@fight.org', 'https://fight.org/', 'Monday - Friday (9AM - 5PM)', 39.95051732018559, -75.16050175338661, TRUE, ARRAY['Health Services', 'Support Services', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('BenePhilly Center', 'Free one-on-one assistance helping Philadelphia residents enroll in public benefit programs to afford essential expenses.', '2029 S 8th St, Philadelphia, PA 19148, USA', 'Philadelphia', 'PA', '191478', '844-848-4376', 'benephilly@phila.gov', 'https://www.phila.gov/programs/benephilly/', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 39.923246470243654, -75.15960559299262, TRUE, ARRAY['Support Services', 'Benefits', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Pennsylvania''s County Assistance Office', 'Helping Pennsylvanians achieve safe, healthy, productive lives through trauma-informed services & accountable resource stewardship.', '5070 Parkside Ave, Philadelphia, PA 19131, USA', 'Philadelphia', 'PA', '19131', '(215) 560-5500', NULL, 'https://www.pa.gov/en/agencies/dhs/contact/cao-information.html', 'Monday - Friday (8AM - 5PM)
Saturday/Sunday (CLOSED)', 39.980375369983776, -75.22160265678014, TRUE, ARRAY['Mental Health', 'Support Services', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Philadelphia Access Center', '20+ year ministry offering social services case coordination, crisis navigation & resource referrals to Philadelphia neighbors.', '1832 S 11th St, Philadelphia, PA 19148, USA', 'Philadelphia', 'PA', '19148', '(215) 389-1985', 'pacinfo@philaccess.org', 'www.philaccess.org', 'Monday-Thursday (9AM - 2PM)
Friday - Sunday (CLOSED)', 39.926238866544, -75.16398586496945, TRUE, ARRAY['Social Services', 'Other', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Lifeline Phone Service', 'Apply for Lifeline phone service online, by phone, or mail. Compare carrier plans to find best fit. Apply: https://nv.fcc.gov/lifeline', '1400 John F Kennedy Blvd, Philadelphia, PA 19107, USA', 'Philadelphia', 'PA', NULL, '(800) 234-9473', 'lifelinesupport@usac.org', 'https://www.lifelinesupport.org/get-started/', 'OPEN 24/7', 39.9526, -75.1652, TRUE, ARRAY['Benefits', 'Other', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Office of Homeless Services', 'Offers emergency shelters, transitional housing, and support services for individuals experiencing homelessness.', '1401 John F Kennedy Blvd #1030, Philadelphia, PA 19102, USA', 'Philadelphia', 'PA', '19102', '(215) 686-7175', 'ohs@phila.gov', 'https://www.phila.gov/departments/office-of-homeless-services/', 'Monday - Friday (8AM - 5PM)
Saturday/Sunday (CLOSED)', 39.9535465, -75.1645161, TRUE, ARRAY['Shelter', 'Housing', 'Support Services']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Mady''s Hands', 'Offering food pantry, nursery pantry with diapers & baby items, HIV testing kits, and clothing bank (call for availability).', '1952 N 24th St, Philadelphia, PA 19121, USA', 'Philadelphia', 'PA', '19121', '(267) 825-5628', 'admin@sistatalkphl.org', 'https://www.7cups.com/local/us/pa/philadelphia/food/my-sistas-resou-7561221613', 'Monday: 1pm-5pm Tuesday: 1pm-5pm Wednesday: 1pm-5pm Thursday: By Appt. Only', 39.9851246, -75.1732971, TRUE, ARRAY['Food', 'Support Services', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Office of Reentry Partnerships', 'ORP provides holistic reentry services to reduce recidivism & enhance opportunities for formerly incarcerated Philadelphia residents.', '1425 Arch St floor 1, Philadelphia, PA 19102, USA', 'Philadelphia', 'PA', '19102', '(215) 683-3370', 'orp@phila.gov', 'https://www.phila.gov/departments/office-of-reentry-partnerships/', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 39.95475670772454, -75.16441048535275, TRUE, ARRAY['Support Services', 'Other', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Office of Reentry and Community Services', 'ORP provides holistic reentry services to reduce recidivism & enhance opportunities for formerly incarcerated Philadelphia residents.', '1401 John F Kennedy Blvd 10th floor, Philadelphia, PA 19102, USA', 'Philadelphia', 'PA', '19102', '(800)-692-7462', NULL, 'https://www.compass.dhs.pa.gov/home/#/', NULL, 39.9526, -75.1652, TRUE, ARRAY['Support Services', 'Other', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Philadelphia Reentry Coalition', 'The Reentry Coalition connects Philadelphia reentry agencies & organizations working together to collectively reduce recidivism.', '1425 Arch St, Philadelphia, PA 19102, USA', 'Philadelphia', 'PA', '19102', '(215) 683-3370', 'kierra.nocho@phila.gov', 'https://www.phlreentrycoalition.org/', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 39.954685031964885, -75.16421448393164, TRUE, ARRAY['Support Services', 'Other', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Friends Rehabilitation Program', 'Supporting marginalized Philadelphia communities with housing, job readiness, social services & partnerships for economic justice.', '704 W Girard Ave, Philadelphia, PA 19123, USA', 'Philadelphia', 'PA', '19123', '(215) 825-8800', 'info@frpinc.org', 'https://friends-frp.org/', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 39.970295254522235, -75.14846406444201, TRUE, ARRAY['Support Services', 'Housing', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('First Step Staffing Philadelphia', 'First Step provides rapid job placement, transportation assistance, training & connections to housing/healthcare for lasting success.', '1231 N Broad St, Philadelphia, PA 19122, USA', 'Philadelphia', 'PA', '19122', '(215) 333-3349', NULL, 'www.firststepstaffing.com', 'Monday - Friday (9AM - 4PM)
Saturday/Sunday (CLOSED)', 39.97296395495297, -75.15892361878328, TRUE, ARRAY['Education', 'Wellness', 'Employment']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Action Wellness', 'Enhancing lives of persons with HIV & high-risk individuals through comprehensive, trauma-informed social services and support.', '1216 Arch St 6th floor, Philadelphia, PA 19107, USA', 'Philadelphia', 'PA', '19107', '(215) 981-0088', NULL, 'www.actionwellness.org', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 39.953971669578856, -75.16035491832508, TRUE, ARRAY['Benefits', 'Life Skills', 'Wellness']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('People for People', 'People for People breaks generational poverty cycles in Philadelphia through life-changing assistance, support services & resources.', '800 N Broad St, Philadelphia, PA 19130, USA', 'Philadelphia', 'PA', '19130', '(215) 235-2340', 'info@peopleforpeople.org', 'www.peopleforpeople.org', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 39.9680763723405, -75.1604021137865, TRUE, ARRAY['Support Services', 'Other', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Diversified Community Services', 'Comprehensive programs empowering youth & families to break poverty cycles, transform communities & build brighter futures for all.', '1920 S 20th St, Philadelphia, PA 19145, USA', 'Philadelphia', 'PA', '19145', '(215) 336-3511', NULL, 'www.dcsphila.org', 'OPEN 24/7', 39.92752914112552, -75.17893299807966, TRUE, ARRAY['Support Services', 'Community Support', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Philadelphia Works', 'Philadelphia Works develops smart workforce solutions that respond to business needs & increase economic opportunity for residents.', '1617 John F Kennedy Blvd Bridge 13th floor, Philadelphia, PA 19103, USA', 'Philadelphia', 'PA', '19103', '(215) 963-2100', 'info@philaworks.org', 'www.philaworks.org', NULL, 39.952968607295865, -75.16650114854545, TRUE, ARRAY['Employment', 'Community Services', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Urban League of Philadelphia', 'Empowering Black Americans & underserved communities toward social equity, economic independence & civil rights through integrated programs.', '1500 John F Kennedy Blvd, Philadelphia, PA 19102, USA', 'Philadelphia', 'PA', '19102', '(215) 985-3220', 'info@urbanleaguephila.org', 'www.urbanleaguephila.org', 'Monday - Friday (9AM - 4PM)
Saturday/Sunday (CLOSED)', 39.953510510262284, -75.16567932722344, TRUE, ARRAY['Support Services', 'Programs', 'Community Support']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('IMPACT Services Corporation', 'Since 1974, helping Kensington residents re-enter workforce, find stable housing & build community through mindful partnerships.', '1952 E Allegheny Ave suite 500, Philadelphia, PA 19134, USA', 'Philadelphia', 'PA', '19134', '(215) 739-1600', 'info@impactservices.org', 'www.impactservices.org', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 39.99433255894427, -75.11174495566915, TRUE, ARRAY['Housing', 'Employment', 'Support Services']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('I''m FREE -Females Reentering Empowering Each Other', 'Females Reentering Empowering Each Other: Woman-centered organization advancing life chances through holistic, therapeutic approaches.', '4700 Wissahickon Ave, Philadelphia, PA 19144, USA', 'Philadelphia', 'PA', '19144', '(215) 951-0330 ext. 2147', 'ImFREEonline@gmail.com', 'www.imfreeonline.org', NULL, 40.01626455272381, -75.17405063220131, TRUE, ARRAY['Support Services', 'Mental Health', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Sisters Returning Home', 'Sisters Returning Home provides comprehensive support to women recently released from Philadelphia jails & PA correctional facilities.', '302 W School House Ln, Philadelphia, PA 19144, USA', 'Philadelphia', 'PA', '19144', '(215) 900-4202', 'info@sistersreturninghome.org', 'www.sistersreturninghome.org', 'Mon-Thurs 9-5', 40.02888570735785, -75.17817115963439, TRUE, ARRAY['Support Services', 'Mental Health', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Youth Sentencing & Reentry Project', 'YSRP works to keep children out of adult jails & prisons, and bring home people sentenced as children to life without parole.', '1528 Walnut St #515, Philadelphia, PA 19102, USA', 'Philadelphia', 'PA', '19102', '(267) 703-8046', 'info@ysrp.org', 'https://www.ysrp.org/', NULL, 39.9494874, -75.1675823, TRUE, ARRAY['Youth', 'Support Services', 'Education']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Community Behavioral Health', 'For 25+ years, Community Behavioral Health has expanded access to mental health services & high-quality care for Philadelphians.', '801 Market St, Philadelphia, PA 19107, USA', 'Philadelphia', 'PA', '19107', '(215) 413-3100', 'CBHMemberPortalSupport@phila.gov', 'cbhphilly.org/contact-list/', 'OPEN 24/7', 39.951641153918594, -75.1536918335943, TRUE, '{}');
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Public Health Management Corporation', 'Public Health Management Corporation builds healthier communities through partnerships, health promotion, education & direct services.', 'Centre Square, 1500 Market St, Philadelphia, PA 19102, USA', 'Philadelphia', 'PA', '19102', '(215) 985-2500', NULL, 'phmc.org', 'Monday - Friday (8:30AM - 5PM)
Saturday/Sunday (CLOSED)', 39.95233972046358, -75.16652794323095, TRUE, ARRAY['Health Services', 'Education', 'Support Services']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Heights Philadelphia', 'From middle school onward: academic, workforce & college support breaking down barriers to propel economic mobility for students.', '123 S Broad St # 850, Philadelphia, PA 19109, USA', 'Philadelphia', 'PA', '19109', '(215) 790-1666', NULL, 'https://heights.org/', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 39.94988535693484, -75.1635769700262, TRUE, ARRAY['Youth Support', 'Education', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Office of Homeless Services', 'Offers emergency shelters, transitional housing, and support services for individuals experiencing homelessness.', '1401 John F Kennedy Blvd #1030, Philadelphia, PA 19102, USA', 'Philadelphia', 'PA', '19102', '(215) 686-7175', 'ohs@phila.gov', 'phila.gov/departments/office-of-homeless-services/', 'Monday - Friday (8AM - 5PM)
Saturday/Sunday (CLOSED)', 39.95416208260039, -75.1644507614079, TRUE, ARRAY['Housing', 'Support Services', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Department of Behavioral Health and Intellectual Disability Services', 'Mental health & substance abuse treatment for individuals with disabilities, emphasizing recovery, resilience & self-determination.', 'Aramark Tower, 1101 Market St, Philadelphia, PA 19107, USA', 'Philadelphia', 'PA', '19107', '(215) 685-5400', 'dbhidscommunications@phila.gov', 'dbhids.org', 'Monday - Friday (8:30AM - 5PM)
Saturday/Sunday (CLOSED)', 39.952141160434024, -75.15839881971432, TRUE, ARRAY['Mental Health', 'Disability Assistance', 'Recovery Support']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Reentry Action Coalition', 'Advocates for policy changes and provides support services for individuals re-entering the community.', '1800 John F Kennedy Blvd Suite 300, Philadelphia, PA 19103, USA', 'Philadelphia', 'PA', '19103', '(267) 238-3800', 'contact@thenrwc.org', 'thenrwc.org/conference/', 'Monday - Friday (9AM - 6PM)
Saturday/Sunday (CLOSED)', 39.953962871198684, -75.17003317535526, TRUE, ARRAY['Support Services', 'Community Support', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Philadelphia Lawyers for Social Justice', 'Offers legal services to individuals experiencing homelessness or re-entering the community.', '230 S Broad St #1102, Philadelphia, PA 19102, USA', 'Philadelphia', 'PA', '19102', '(267) 519-5323', 'info@plsephilly.org', 'plsephilly.org/', NULL, 39.9484052765602, -75.16515737301322, TRUE, ARRAY['Legal Assistance', 'Support Services', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('The People''s Paper Co-Op', 'Connects formerly incarcerated individuals with artists, lawyers, and others to develop skills and advocate for themselves.', '2544 Germantown Ave, Philadelphia, PA 19133, USA', 'Philadelphia', 'PA', '19133', '(215) 225-7830', 'info@villagearts.org', 'peoplespaperco-op.weebly.com/', 'Monday - Friday (10AM - 6PM)
Saturday/Sunday (CLOSED)', 39.9908877, -75.1482668, TRUE, ARRAY['Support Services', 'Community Support', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Office of Student Rights and Responsibilities', 'We ensure homeless children & youth enroll, participate & succeed in school using McKinney-Vento Act authorized activities & practices.', '440 N Broad St, Philadelphia, PA 19130, USA', 'Philadelphia', 'PA', '19130', '(215) 400-4830', NULL, 'philasd.org/studentrights/#homeless', 'Monday - Friday (8AM - 5PM)
Saturday/Sunday (CLOSED)', 39.96097270683761, -75.16236870239791, TRUE, ARRAY['Homelessness', 'Young Adults', 'Continuing Education']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('The Philadelphia School', '50+ years of progressive PreK-8 education creating confident, curious, compassionate children through real-world learning partnerships.', '2501 Lombard St, Philadelphia, PA 19146, USA', 'Philadelphia', 'PA', '19146', '(215) 545-5323', NULL, 'https://www.tpschool.org/', 'Monday - Friday (7:30AM - 5:30PM)
Saturday/Sunday (CLOSED)', 39.94684655179244, -75.18227799654116, TRUE, ARRAY['Young Adults', 'Counseling', 'Mental Health Services']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Mazzoni Center – Washington West', 'The Mazzoni Center provides quality comprehensive health & wellness services in an LGBTQ-focused environment preserving dignity.', '1201 Locust St, Philadelphia, PA 19107, USA', 'Philadelphia', 'PA', '19107', '(215) 985-9206', NULL, 'mazzonicenter.org/about-us/contact-us', 'Monday - Friday (10AM - 6PM)
Saturday/Sunday (CLOSED)', 39.947833106303875, -75.16090015260205, TRUE, ARRAY['Support Services', 'Counseling', 'Mental Health Services']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Mazzoni Center – Bainbridge', 'The Mazzoni Center provides quality comprehensive health & wellness services in an LGBTQ-focused environment preserving dignity.', '1348 Bainbridge St, Philadelphia, PA 19147, USA', 'Philadelphia', 'PA', '19147', '(215) 563-0652', NULL, 'mazzonicenter.org/about-us/contact-us', 'Monday - Thursday (8AM - 9PM)
Friday (8AM - 5PM)
Saturday/Sunday (CLOSED)', 39.94262288982232, -75.1651136890522, TRUE, ARRAY['Support Services', 'Counseling', 'Mental Health Services']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Second Chances Ministries', 'Philadelphia church that solely embraces the Word of God as the foundation for existence, survival, and faith community.', '1516 N 5th St Unit 101, Philadelphia, PA 19122, USA', 'Philadelphia', 'PA', NULL, '215-662-0246', NULL, '2ndchance-ministries.org', 'Monday - Friday (9AM - 4:30PM)
Saturday/Sunday (CLOSED)', 39.97451473316916, -75.14422641698347, TRUE, ARRAY['Support Services', 'Counseling', 'Mental Health Services']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Building 21', 'Safe, equitable environment where ALL students tap into passions through personalized learning, project-based experiences & growth mindset.', '6501 Limekiln Pike, Philadelphia, PA 19138, USA', 'Philadelphia', 'PA', '19138', '(215) 400-7450', NULL, 'https://building21.philasd.org/', 'Monday - Thursday (7:45AM - 3PM)
Friday (7:45AM - 1PM)
Saturday/Sunday (CLOSED)', 40.05366264819684, -75.15263621839846, TRUE, ARRAY['Support Services', 'Counseling', 'Mental Health Services']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Community College of Philadelphia', 'Offers affordable credit and non-credit programs, including workforce development and adult education, to help individuals re-entering the community find employment.', 'Community College of Philadelphia, 1700 Spring Garden St, Philadelphia, PA 19121, USA', 'Philadelphia', 'PA', NULL, NULL, NULL, 'ccp.edu', 'Monday - Thursday (7AM–10PM)
Friday (7 AM–6 PM)
Saturday  (7 AM–5 PM)
Sunday (CLOSED)', 39.96196376703448, -75.16598584679281, TRUE, ARRAY['Support Services', 'Counseling', 'Mental Health Services']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Lutheran Settlement House', 'Since 1902, LSH empowers Philadelphia families through domestic violence services, emergency shelter, food assistance & senior programs.', '1340 Frankford Ave, Philadelphia, PA 19125, USA', 'Philadelphia', 'PA', NULL, '(215) 426-8610', NULL, 'lutheransettlement.org', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 39.97146959737574, -75.13460645272639, TRUE, ARRAY['Support Services', 'Counseling', 'Mental Health Services']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Lutheran Settlement House', 'Since 1902, LSH empowers Philadelphia families through domestic violence services, emergency shelter, food assistance & senior programs.', '1007 W Lehigh Ave, Philadelphia, PA 19133, USA', 'Philadelphia', 'PA', NULL, '(215) 426-8610', NULL, 'lutheransettlement.org', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 39.99329539557329, -75.14837084042995, TRUE, ARRAY['Support Services', 'Counseling', 'Mental Health Services']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('The Center for Carceral Communities', 'The Center for Carceral Communities, an initiative of the School of Social Policy & Practice at the University of Pennsylvania works collaboratively with neighborhoods in West Philadelphia to help people with a history of incarceration re-engage with the community. We provide free, evidence-based psychosocial services that address the mental health, educational, housing, advocacy and primary care challenges confronting those returning to the community. The Center seeks to reverse the community-to-prison pipeline by helping participants harness their strengths and become leaders in the community.', '4020 Market St, Philadelphia, PA 19104, USA', 'Philadelphia', 'PA', '19104', '267-538-0180', 'noam@thecenterphilly.com', 'thecenterphilly.com/', NULL, 39.957079698297036, -75.20285664234966, TRUE, ARRAY['Support Services', 'Counseling', 'Mental Health Services']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Low-Income Home Energy Assistance Program (LIHEAP)', 'LIHEAP helps keep your home warm & safe. Apply Nov 4, 2024-Apr 18, 2025 for $200-$1,000 cash grants sent directly to your utility.', '1163 S Broad St, Philadelphia, PA 19147, USA', 'Philadelphia', 'PA', NULL, '(866)-857-7095', NULL, 'https://www.pa.gov/services/dhs/apply-for-the-low-income-home-energy-assistance-program-liheap', 'Monday - Friday (8AM - 5PM)
Saturday/Sunday (CLOSED)', 39.9358891801595, -75.16686332989664, TRUE, ARRAY['Support Services', 'Counseling', 'Mental Health Services']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Esperanza College of Eastern University', 'Start at any life stage at Esperanza College, even if English is your second language. Transformational faith, reason & justice.', '4417 N 6th St, Philadelphia, PA 19140, USA', 'Philadelphia', 'PA', '19140', '215-324-0746', NULL, 'https://esperanza.eastern.edu/', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 40.01890642364248, -75.13665002048472, TRUE, ARRAY['Support Services', 'Counseling', 'Mental Health']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Delaware County Family Service Center', 'Comprehensive services including residential treatment, family services, foster care, adoption, immigration help & senior programming.', '1260 E Woodland Ave #212, Springfield, PA 19064, USA', 'Philadelphia', 'PA', '19013', '610-876-7101', 'cssphiladelphia@chs-adphila.org', 'cssphiladelphia.org', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 39.908968287578304, -75.33045831802741, TRUE, ARRAY['Support Services', 'Homelessness', 'Counseling']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('The Cenacle at Padre Pio Center', 'The Cenacle supports pregnant women, new parents & families with parenting education, food pantries, health literacy & workshops.', '1527 Church St, Philadelphia, PA 19124, USA', 'Philadelphia', 'PA', '19124', '267-453-0090', 'cssphiladelphia@chs-adphila.org', 'cssphiladelphia.org', NULL, 40.011768497680386, -75.08975495743819, TRUE, ARRAY['Support Services', 'Women', 'Family Reintegration Support']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Catholic Social Services: Northeast', 'Comprehensive services including residential treatment, family services, foster care, adoption, immigration help & senior programming.', '7340 Jackson St, Philadelphia, PA 19136, USA', 'Philadelphia', 'PA', '19136', '215-624-5920', 'cssphiladelphia@chs-adphila.org', 'cssphiladelphia.org', 'Monday - Friday (8:30AM - 4:30PM)
Saturday/Sunday (CLOSED)', 40.03321079433493, -75.03538858580227, TRUE, ARRAY['Support Services', 'Homelessness', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Catholic Social Services', 'Comprehensive services including residential treatment, family services, foster care, adoption, immigration help & senior programming.', '222 N 17th St, Philadelphia, PA 19103, USA', 'Philadelphia', 'PA', '19103', '215-587-3555', 'cssphiladelphia@chs-adphila.org', 'cssphiladelphia.org', 'Monday - Friday (8:30AM - 4:30PM)
Saturday/Sunday (CLOSED)', 39.95752549944076, -75.16766733816495, TRUE, ARRAY['Support Services', 'Homelessness', 'Counseling']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Youth Sentencing & Reentry Project', 'Provides legal representation and reentry support to youth prosecuted in the adult criminal justice system.', '1528 Walnut St # 515, Philadelphia, PA 19102, USA', 'Philadelphia', 'PA', '19102', '267-703-8046', 'info@ysrp.org', 'ysrp.org', NULL, 39.94967860030689, -75.16729100372838, TRUE, ARRAY['Young Adults', 'Legal Assistance', 'Support Services']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('The ReAwakening Agency', 'Supporting reentry with basic necessities, hygiene products, food, career/education mentorship & community engagement programs.', '1114 S 23rd St, Philadelphia, PA 19146, USA', 'Philadelphia', 'PA', NULL, '(267) 241-7319', 'thereawakeagency@gmail.com', 'https://www.aftertheawakening.org/', NULL, 39.9388557, -75.1817023, TRUE, ARRAY['Support Services', 'Clothing Assistance', 'Life Skills']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Pennsylvania Prison Society', 'Supporting incarcerated individuals & families through support lines, SCI prison transportation, mentorship & prison advocacy work.', '230 S Broad St #605, Philadelphia, PA 19102, USA', 'Philadelphia', 'PA', '19102', '215-564-4775', 'helpline@prisonsociety.org customerservice@prisonsociety.org', 'prisonsociety.org/', NULL, 39.94835909895764, -75.16498234408506, TRUE, ARRAY['Support Services', 'Family Reintegration Support', 'Community Reintegration']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Why Not Prosper Transitional House for Formerly Incarcerated Women', 'Empowers women returning from prison with support groups, employment skills, housing/legal services, food & behavioral health support.', '717 E Chelten Ave, Philadelphia, PA 19144, USA', 'Philadelphia', 'PA', '19144', '610-716-1113', 'whynotprosper@aol.com', 'why-not-prosper.org/', 'Monday - Friday (9AM - 4PM)
Saturday/Sunday (CLOSED)', 40.04475439523725, -75.1656853567775, TRUE, ARRAY['Women', 'Counseling', 'Support Services']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Brown Reentry Consulting', 'Black-owned consulting firm providing individualized, person-centered employment & housing support for formerly incarcerated individuals.', '601 Upland Ave, Brookhaven, PA 19015, USA', 'Philadelphia', 'PA', '19105', '(267) 225-7899', 'admin@brownreentryconsulting.com', 'brownreentryconsulting.org/', 'Monday - Friday (10AM - 5PM)
Saturday/Sunday (CLOSED)', 39.85519826876763, -75.37854957927385, TRUE, ARRAY['Support Services', 'Employment', 'Jobs']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('The Simple Way', 'Food Pantry, Support Services, Neighborhood Gatherings.', '3234 Potter St, Philadelphia, PA 19134, USA', 'Philadelphia', 'PA', '19134', '(215) 423-3598', 'INFO@THESIMPLEWAY.ORG', 'thesimpleway.org/', NULL, 39.99783368940796, -75.11212933458826, TRUE, ARRAY['Support Services', 'Homelessness', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Pennsylvania Health Law Project', 'PHLP offers advice & coaching for self-advocacy, plus legal representation in hearings & other forums when professional help is needed.', '123 Chestnut St, Philadelphia, PA 19106, USA', 'Philadelphia', 'PA', '19106', '(800) 274-3258', 'staff@phlp.org', 'https://www.phlp.org/en/', 'Monday - Friday 9AM - 5PM)
Saturday/Sunday (CLOSED)', 39.9483489, -75.1438071, TRUE, ARRAY['Benefits', 'Homelessness', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Mamie Nichols Center', 'Assists Philadelphia residents achieve financial stability through public benefits screening, application completion & enrollment follow-up.', '1529 S 22nd St, Philadelphia, PA 19146, USA', 'Philadelphia', 'PA', '19145', '(215) 336-5505', 'intake@gpca-phila.org', 'https://gpca-phila.org', NULL, 39.93253814431196, -75.1811976224768, TRUE, ARRAY['Support Services', 'Homelessness', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Face To Face', 'Protects rights of low-income & homeless individuals through volunteer attorneys providing legal services, utility & housing assistance.', '123 E Price St, Philadelphia, PA 19144, USA', 'Philadelphia', 'PA', '19144', '(215) 438-7939', NULL, 'facetofacegermantown.org/', 'Monday - Thursday (9 AM–3 PM)
Tuesday/Wednesday (CLOSED)', 40.03835019842051, -75.17413138051012, TRUE, ARRAY['Legal Assistance', 'Homelessness', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Philadelphia VIP', 'Community-powered volunteer estate planning program ensuring access to justice for low-income Philadelphians & vulnerable populations.', '1500 John F Kennedy Blvd #1850, Philadelphia, PA 19102, USA', 'Philadelphia', 'PA', '19102', '(215) 523-9550', 'phillyvip@phillyvip.org', 'phillyvip.org', 'Monday - Thursday (9AM - 5PM)
Friday (9AM - 3PM)
Saturday/Sunday (CLOSED)', 39.94919301474018, -75.16620528314392, TRUE, ARRAY['Housing Assistance', 'Homelessness', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Pennsylvania Health Access Network', 'This program offers free health insurance enrollment assistance to ensure you get the best coverage for your family.', '1501 Cherry St, Philadelphia, PA 19102, USA', 'Philadelphia', 'PA', '19102', '(877) 570-3642', NULL, 'pahealthaccess.org/gethelp/', 'Monday - Friday 9AM - 9:30PM)
Saturday/Sunday (CLOSED)', 39.95580864467246, -75.16504057307674, TRUE, ARRAY['Insurance', 'Homelessness', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Help at Home', 'Help at Home (OPTIONS program) provides assistance to Pennsylvania residents age 60+ who would like to stay in their own homes.', '1500 Spring Garden St floor 6 suite b, Philadelphia, PA 19130, USA', 'Philadelphia', 'PA', '19130', '215-515-9926', 'PAinfo@helpathome.com', 'https://www.helpathome.com/', 'Monday - Friday (8AM - 5PM)
Saturday/Sunday (CLOSED)', 39.962538834547885, -75.16420622933506, TRUE, ARRAY['Caretaking', 'Homelessness', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Philadelphia Lawyers for Social Equity', 'PLSE provides free legal representation & assistance with criminal record expungement and pardons to help overcome reentry barriers.', '230 S Broad St suite 1102, Philadelphia, PA 19102, USA', 'Philadelphia', 'PA', '19102', '(267) 519-5323', 'info@plsephilly.org', 'plsephilly.org', NULL, 39.948394950369234, -75.16506452819354, TRUE, ARRAY['Legal Assistance', 'Homelessness', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Community Legal Services', 'Community Legal Services offers free legal assistance in civil matters, including reentry legal issues, housing, employment & benefits.', '1410 W Erie Ave, Philadelphia, PA 19140, USA', 'Philadelphia', 'PA', '19140', '(215) 227-2400', NULL, 'clsphila.org/', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 40.00914918387382, -75.15200245871378, TRUE, ARRAY['Legal Assistance', 'Homelessness', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Community Legal Services', 'Community Legal Services offers free legal assistance in civil matters, including reentry legal issues, housing, employment & benefits.', '1424 Chestnut St, Philadelphia, PA 19102, USA', 'Philadelphia', 'PA', '19102', '(215) 981-3700', NULL, 'clsphila.org/', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 39.95091141535426, -75.1652321171963, TRUE, ARRAY['Legal Assistance', 'Homelessness', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('ShopRite Supermarket', 'Secondchance employer with positions available – Applications accepted on a rolling basis.', 'S 24th St & Oregon Ave, Philadelphia, PA 19145, USA', 'Philadelphia', 'PA', '19145', '(215) 336-7300', 'pchr@phila.gov', 'https://www.shoprite.com/sm/pickup/rsid/3000/BrownsSuperStores', 'Monday - Friday (7AM - 11PM)
Saturday/Sunday (7AM - 11PM)', 39.919680551888135, -75.18647747536926, TRUE, ARRAY['Employment', 'Jobs', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('ShopRite Supermarket', 'Secondchance employer with positions available – Applications accepted on a rolling basis.', '3400 Fox St unit a, Philadelphia, PA 19129, USA', 'Philadelphia', 'PA', '19129', '(215) 717-1222', 'pchr@phila.gov', 'https://www.shoprite.com/sm/pickup/rsid/3000/BrownsSuperStores', 'Monday - Friday (7AM - 11PM)
Saturday/Sunday (7AM - 11PM)', 40.00949780641033, -75.17457024583268, TRUE, ARRAY['Employment', 'Jobs', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Planet Fitness', 'Secondchance employer with positions available – Applications accepted on a rolling basis.', '2350 Oregon Ave, Philadelphia, PA 19145, USA', 'Philadelphia', 'PA', '19145', '(215) 551-9000', NULL, 'https://www.planetfitness.com/gyms/philadelphia-south-philly-pa', 'Tuesday - Thursday (OPEN 24 HOURS)
Friday (12 AM – 9 PM)
Saturday/Sunday (6 AM – 9 PM)
Monday (5 AM – 12 AM)', 39.9186412, -75.18880530000001, TRUE, ARRAY['Employment', 'Jobs', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('City Fitness', 'Secondchance employer with positions available – gym cleaner or personal trainer.', '1819 John F Kennedy Blvd, Philadelphia, PA 19103, USA', 'Philadelphia', 'PA', '19103', '(215) 302-2300', 'logansquare@cityfitnessphilly.com', 'https://cityfitnessphilly.com/logan-square/', 'Monday - Thursday (5 AM – 11 PM)
Friday (5 AM – 9 PM)
Saturday/Sunday (6 AM – 9 PM)', 39.95452315923421, -75.17056154376449, TRUE, ARRAY['Employment', 'Jobs', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('City Fitness', 'Secondchance employer with positions available – gym cleaner or personal trainer.', '2112 Fairmount Ave, Philadelphia, PA 19130, USA', 'Philadelphia', 'PA', '19130', '(267) 534-3435', 'fairmount@cityfitnessphilly.com', 'https://cityfitnessphilly.com/fairmount-club/', 'Monday - Thursday (5 AM – 11 PM)
Friday (5 AM – 9 PM)
Saturday/Sunday (6 AM – 9 PM)', 39.96716630547303, -75.17274128948539, TRUE, ARRAY['Employment', 'Jobs', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('United Parcel Service', 'Secondchance employer with positions available – applications are accepted on a rolling basis.', '15 E Oregon Ave, Philadelphia, PA 19148, USA', 'Philadelphia', 'PA', '19148', '(888) 742-5877', NULL, 'https://locations.ups.com/us/en/pa/philadelphia/customer-center-004097.html', 'PERMANENTLY CLOSED', 39.913582552709116, -75.14464652175505, TRUE, ARRAY['Employment', 'Jobs', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Community Integrated Services', 'Available job openings as Business Development Specialist and Job Coaches. Second chance employer.', '441 N 5th St suite 101, Philadelphia, PA 19123, USA', 'Philadelphia', 'PA', '19123', '(215) 238-7411', 'info@cisworks.org', 'cisworks.org/', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 39.95905844770063, -75.14692668167235, TRUE, ARRAY['Employment', 'Jobs', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('FedEx Ship Center', 'FedEx is a second chance employer, and are accepting applications for shipping, receiving, and forklift.', '3600 Grays Ferry Ave, Philadelphia, PA 19146, USA', 'Philadelphia', 'PA', '19146', '(800) 463-3339', NULL, 'https://local.fedex.com/en-us/pa/philadelphia/muva?cmp=LOC-1001545-3-2-971-1110000-US-US-EN-GPLDROPOFFBOXES', 'Monday - Friday (8:30 AM – 7:30 PM)
Saturday  (9AM – 5 PM)
Sunday (CLOSED)', 39.939510471726095, -75.20144344860955, TRUE, ARRAY['Employment', 'Jobs', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('SP Plus Parking', 'Second Chance Employer. Has contracts all throughout the city for parking garages, security, and the sporting stadiums in Philadelphia.', '10 S 8th St, Philadelphia, PA 19106, USA', 'Philadelphia', 'PA', '19017', '(215) 568-4018', NULL, 'spplus.com/', NULL, 39.94963625031996, -75.16810984156376, TRUE, ARRAY['Employment', 'Jobs', 'Benefits']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('ACHIEVEability', 'We partner with families experiencing or at-risk-of homelessness, providing housing & supportive services to break poverty cycles.', '5901 Market St suite 410, Philadelphia, PA 19139, USA', 'Philadelphia', 'PA', '19139', '(215) 748-8800', 'info@achieve-ability.org', 'achieveability.org/aboutus', 'Monday - Thursday (9AM - 5PM)
Friday (9AM - 1PM)
Saturday/Sunday (CLOSED)', 39.96206457094292, -75.23913350306893, TRUE, ARRAY['Housing Assistance', 'Homelessness', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Horizon House Supported Employment Services', 'Horizon House provides programs & services for adults with behavioral health needs, intellectual/developmental disabilities & homeless.', '5901 Market St 3rd floor, Philadelphia, PA 19139, USA', 'Philadelphia', 'PA', '19139', '(215) 386-3838', 'Horizon.House@hhinc.org', 'hhinc.org/about-us/', NULL, 39.962055139902645, -75.2391349374777, TRUE, ARRAY['Caretaking', 'Homelessness', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('People Advancing Reintegration Recycle Works', 'This is a non-profit electronics recycler that provides transitional employment to people returning from prison.', '2024 W Hunting Park Ave, Philadelphia, PA 19140, USA', 'Philadelphia', 'PA', '19140', '(267) 335-5455', 'info@par-recycleworks.org', 'par-recycleworks.org/', 'Monday - Friday (8 AM–2:30 PM)
Saturday/Sunday (CLOSED)', 40.01226155782497, -75.16112269877883, TRUE, ARRAY['Employment', 'Disability', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Uplift Workforce Solutions', 'Uplift Solutions removes barriers to success through workforce development training in HVAC, CDL & more to alleviate poverty in underserved areas.', '417 N 8th St, Philadelphia, PA 19123, USA', 'Philadelphia', 'PA', '19123', '(833) 875-4389', 'communications@upliftsolutions.org', 'upliftsolutions.org/', NULL, 39.95918918746169, -75.15158596595128, TRUE, ARRAY['Employment', 'Disability', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Inglis Employment Services', 'IES provides hands-on supported employment services such as skill building, training, and partnership to assist those with disabilities.', '2560 Belmont Ave, Philadelphia, PA 19131, USA', 'Philadelphia', 'PA', '19131', '(267) 295-5400', 'community@inglis.org', 'https://www.inglis.org/programs-and-services/innovation-center', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 39.99920071259143, -75.21981212844187, TRUE, ARRAY['Employment', 'Disability', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Philadelphia Opportunities Industrialization Center', 'Philadelphia OIC provides workforce development, education, and vocational job training programs to help individuals secure employment.', '1231 N Broad St, Philadelphia, PA 19122, USA', 'Philadelphia', 'PA', '19122', '215-236-7700', 'hello@oicphila.org', 'oicphila.org/', 'Monday - Friday (8:30 AM – 4:30 PM)
Saturday/Sunday (CLOSED)', 39.972969624581665, -75.15872758440663, TRUE, ARRAY['Employment', 'Low Income', 'Disability']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('PA CareerLink North', 'CareerLink offers job search assistance, career counseling, skills training, and other employment resources.', '4261 N 5th St, Philadelphia, PA 19140, USA', 'Philadelphia', 'PA', '19140', '(215) 967-9711', NULL, 'pacareerlink.pa.gov/', 'Monday - Friday (8AM – 4:30 PM)
Saturday/Sunday (CLOSED)', 40.016464246552644, -75.13466091376526, TRUE, ARRAY['Employment', 'Low Income', 'Disability']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('PA CareerLink West', 'CareerLink offers job search assistance, career counseling, skills training, and other employment resources.', '3901 Market St, Philadelphia, PA 19104, USA', 'Philadelphia', 'PA', '19104', '(215) 473-3630', NULL, 'pacareerlink.pa.gov/', 'Monday - Friday (8AM – 4:30 PM)
Saturday/Sunday (CLOSED)', 39.95729926401547, -75.20149898827991, TRUE, ARRAY['Employment', 'Low Income', 'Disability']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('PA CareerLink Suburban Station', 'CareerLink offers job search assistance, career counseling, skills training, and other employment resources.', '1617 John F Kennedy Blvd #200, Philadelphia, PA 19103, USA', 'Philadelphia', 'PA', '19103', '(215) 557-2592', NULL, 'pacareerlink.pa.gov/', 'Monday - Friday (8AM – 4:30 PM)
Saturday/Sunday (CLOSED)', 39.95418792283914, -75.16738044108996, TRUE, ARRAY['Employment', 'Low Income', 'Disability']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Utilities Emergency Services Fund', 'Rapid placement into temporary housing for homeless individuals & families, with pathway support to secure permanent housing solutions.', '1608 Walnut St #600, Philadelphia, PA 19103, USA', 'Philadelphia', 'PA', '19103', '(215) 972-5170', NULL, 'https://uesfacts.org/', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 39.9497107746814, -75.16805841761692, TRUE, ARRAY['Housing Assistance', 'Homelessness', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('H.E.L.P. Philadelphia', 'The facility provides 50 transitional apartments for homeless families and 40 permanent townhouses for low-income families.', '1500 Market St, Philadelphia, PA 19102, USA', 'Philadelphia', 'PA', '19131', '(215) 473-7451', 'info@phdc.phila.gov', 'https://phdcphila.org/', NULL, 39.95209420573439, -75.16685383177212, TRUE, ARRAY['Housing Assistance', 'Homelessness', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Community Residential Rehabilitation Services', 'This program assists individuals with chronic mental illness live in a group home setting.', '9350 Ashton Rd suite 201, Philadelphia, PA 19114, USA', 'Philadelphia', 'PA', '19136', '(215) 386-3838', 'clhs@jevs.org', 'https://www.jevshumanservices.org/program/community-residential-rehabilitation-services/', 'Monday – Friday
8 am – 4 pm', 39.96204288418685, -75.23913910598966, TRUE, ARRAY['Housing Assistance', 'Homelessness', 'Mental Health Services']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Bridge House Transitional Housing', 'Serves women from shelters by providing safe, supportive housing for up to twelve months while they develop self-sufficiency skills', '4300 Monument Rd, Philadelphia, PA 19131, USA', 'Philadelphia', 'PA', '19131', '(215) 877-1925', 'contactus@methodistservices.org', 'https://www.findhelp.org/methodist-services--philadelphia-pa--bridge-house-transitional-housing/4957206332047360?postal=19019', 'Monday - Friday (8:30 AM – 6PM)
Saturday/Sunday (CLOSED)', 39.9978971, -75.2145893, TRUE, ARRAY['Housing Assistance', 'Women', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Our Closet In Your Neighborhood', 'OCIYN is a free mobile program providing food, clothing & services through pop-up shops at churches, hospitals & community sites.', '345 Montgomery Ave, Bala Cynwyd, PA 19004, USA', 'Philadelphia', 'PA', '19004', '(267) 256-2179', 'info-ociyn@jfcsphilly.org', 'https://jfcsphilly.org/our-closet-in-your-neighborhood/', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 40.006241512978505, -75.24432686937354, TRUE, ARRAY['Housing Assistance', 'Homelessness', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Project HOME Outreach Coordination Center', 'Project HOME''s OCC coordinates street outreach to homeless Philadelphians, building trust to connect people with stabilizing services.', '1515 Fairmount Ave, Philadelphia, PA 19130, USA', 'Philadelphia', 'PA', '19131', '(215) 232-1984', NULL, 'projecthome.org/outreach-coordination-center', 'OPEN 24/7', 39.967328342728926, -75.16292530784942, TRUE, ARRAY['Support Services', 'Other', 'Other']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Project HOME', 'Project HOME provides supportive housing, employment assistance, and other services to help individuals break the cycle of homelessness.', '2826 W Diamond St, Philadelphia, PA 19121, USA', 'Philadelphia', 'PA', '19130', '(215) 232-7272', NULL, 'projecthome.org', NULL, 39.96726425698941, -75.16296469072131, TRUE, ARRAY['Housing Assistance', 'Homelessness', 'Low Income']);
INSERT INTO public.resources (name, description, address, city, state, zip_code, phone, email, website, hours, latitude, longitude, is_published, tags) VALUES ('Philadelphia Housing Authority', 'Philadelphia Housing Authority provides affordable housing options & comprehensive support services for eligible individuals & families.', '2013 Ridge Ave, Philadelphia, PA 19121, USA', 'Philadelphia', 'PA', '19121', '(215) 684-4000', 'info@pha.phila.gov', 'pha.phila.gov', 'Monday - Friday (9AM - 5PM)
Saturday/Sunday (CLOSED)', 39.97669587180632, -75.16894324090042, TRUE, ARRAY['Housing Assistance', 'Disability', 'Low Income']);

-- Events (8 rows)
INSERT INTO public.events (title, description, location, instructor, event_date, end_date, is_published) VALUES ('$1 Million Celebration', 'Philadelphia, PA – The Fountain Fund’s Philadelphia site is pleased to announce that it recently surpassed the $1 million mark in loans made to its Client Partners. This is a significant milestone in fulfilling the agency’s mission of increasing economic opportunities for formerly incarcerated people to improve their lives and remain in their communities.   Since 2022, the agency’s Philadelphia office has provided 137 low-interest loans and financial coaching to more than 131 returning citizens. Support from the GreenLight Fund has been instrumental in the agency’s successful launch and emergence as leader in the reentry community.   Shares Michael Butler, Philadelphia Site Director, “Every person who receives a loan has a powerful story to tell. We see their disbelief turning into joy, the weight of anxiety lifted, the spark of hope reignited. We also hear gratitude for simply being given a chance.” He continues, “Today, we don’t just acknowledge that, we celebrate it. We celebrate this milestone in the heart of the City of Brotherly Love, where giving folks chances are honored, and where an organization has entrusted this sacred work to one of its own, someone who has carried the same scars of life behind the wall and now stands as proof of what is possible.”   The Fountain Fund believes that everyone they help stand strong is one less person caught in the cycle of a broken system. That’s REAL recidivism prevention. An inspiring example: Client Partner Tyree Wallace was incarcerated for 26 years for a crime he didn’t commit. In fall 2024, he returned home to begin life anew. His dream? To launch the Systemic Reformative Change Foundation, a nonprofit that is committed to transforming the systemic injustices that oppress marginalized communities. A $15,000 Fountain Fund loan is helping Tyree fulfill this longtime vision.   Stacey Torrance, Philadelphia Loan Administrator, works closely with Client Partners during the loan review process. He shares, “From someone who served three decades of a death by incarceration sentence, I know how it feels to have unfulfilled and unattainable dreams because you are invisible to financial institutions and the credit system. The Fountain Fund removes those barriers. Financial empowerment IS criminal justice reform.”   The Fountain Fund is headquartered in Charlottesville, VA. Founded in 2017, the nonprofit also provides services in Boston, MA; New Orleans, LA; Philadelphia, PA; and Richmond, VA.   Note: Press is invited to attend the RSVP only $1M Milestone Event taking place on October 14, 2025 from 5-7pm at Hopeworks Kensington, 3400 J Street, Philadelphia, PA.', NULL, 'The Fountain Fund', '2025-10-14T21:00:00.000Z', '2025-10-14T23:00:00.000Z', TRUE);
INSERT INTO public.events (title, description, location, instructor, event_date, end_date, is_published) VALUES ('Record Clearing Event', 'Record Clearing Clinic', NULL, 'Office of Reentry Partnerships', '2025-02-20T16:00:00.000Z', '2025-02-20T18:00:00.000Z', TRUE);
INSERT INTO public.events (title, description, location, instructor, event_date, end_date, is_published) VALUES ('meeting at Brown Reentry Consulting', 'meeting to talk about their services and how often they hire.', '601 Upland Ave', 'Dillon DeRosato', '2025-05-17T16:00:00.000Z', '2025-05-17T17:00:00.000Z', TRUE);
INSERT INTO public.events (title, description, location, instructor, event_date, end_date, is_published) VALUES ('Job Fair', 'Job Fair which includes city municipal jobs like street maintenance, civil assistance, or transit repair. There are also businesses looking for your information, today there are [ Wholefoods, PepBoys, Acme, WalMart, Dave & Buster''s ]', '3901 Market St Philadelphia', 'Dave Smith', '2025-05-14T15:00:00.000Z', '2025-05-14T20:00:00.000Z', TRUE);
INSERT INTO public.events (title, description, location, instructor, event_date, end_date, is_published) VALUES ('Interview with SP Plus Parking', 'interview with amanda', '1608 Walnut St, 8th Floor Philadelphia', 'Amanda Braccia', '2025-05-16T13:30:00.000Z', NULL, TRUE);

-- Courses (47 rows)
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Before You Purchase an Apartment', 'Here''s a quick video of five things you should consider or research when moving into your first apartment.', 'Housing', NULL, 'https://youtube.com/shorts/RVl_rz6UG8M', FALSE, FALSE, TRUE, NULL);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Manage a Savings Account', 'Find ways to keep money aside for future plans. Understanding the way these accounts earn interest is one great way to increase your savings further.

Use the button below to review this Course.', 'Financial Literacy', 'https://tdbank.everfi-next.net/student/dashboard/td-learning/tdbank-investing-in-your-future/savings-accounts-achieve?locale=en', NULL, TRUE, FALSE, TRUE, NULL);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('How to Use 401(k) Plans', 'In order to plan for your ideal retirement, these tips can help you set a strong foundation for reaching the future you’re dreaming of.

Use the button below to review this Course.', 'Financial Literacy', 'https://tdbank.everfi-next.net/student/dashboard/td-learning/tdbank-preparing-for-retirement/1714?locale=en#401k-plans/getting-started/page-1', NULL, TRUE, FALSE, TRUE, NULL);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Investing in Your Future', 'Here are multiple self-tasks which help you collect, review, and manage things like your money, taxes, debt, and identification.', 'Financial Literacy', 'https://tdbank.everfi-next.net/student/dashboard/td-learning/tdbank-building-financial-capability?locale=en', NULL, TRUE, FALSE, TRUE, NULL);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Emergency Savings', 'Building an emergency savings account that is dedicated to handling the unexpected is important.', 'Financial Literacy', 'https://tdbank.everfi-next.net/student/dashboard/td-learning/tdbank-investing-in-your-future/building-emergency-savings?locale=en', NULL, TRUE, FALSE, TRUE, NULL);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Budgeting for Beginners', 'Here is a step by step guide on how to create a personal budget from scratch, plus a free included spreadsheet for you to use.', 'Financial Literacy', NULL, 'https://youtu.be/-vVp185Sq24', TRUE, FALSE, TRUE, NULL);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Three E''s of Reentry', 'Check out this video from Nick Crasper who speaks on programs that work for individuals that were recently incarcerated.', 'Community Support', NULL, 'https://youtu.be/aEWUg1zeUsg', FALSE, FALSE, TRUE, NULL);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Getting Employed with a Criminal Record', 'Individuals with criminal records can overcome employment barriers through planned resume prep, building interview skills, and utilizing resources.', 'Employment', NULL, 'https://youtu.be/FGFjZlfL9ms', FALSE, FALSE, TRUE, NULL);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Creating SMART GOALS', 'How to set proper goals for yourself when planning your future career. Try this presentation with Nicole.', 'Employment', NULL, 'https://youtu.be/2KWEe1SQa2g', FALSE, FALSE, TRUE, NULL);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('How to Write a Great Resume', 'Here are 8 tips for starting to collect your information and present it to employers, helping connect you to the jobs which work best for you.', 'Employment', NULL, 'https://youtu.be/u75hUSShvnc', TRUE, FALSE, TRUE, NULL);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Your First Apartment Checklist', 'Check out this video describing the things you will need moving into your first apartment.', 'Housing', NULL, 'https://youtu.be/vPS9Bn-Vw2c', FALSE, FALSE, TRUE, NULL);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Money Smart Courses', 'https://playmoneysmart.fdic.gov/games', 'Basic Needs', NULL, NULL, TRUE, FALSE, TRUE, 1);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Mentorship Programs', 'Pairing individuals with mentors who can provide guidance and support.', 'Community Support', NULL, NULL, FALSE, TRUE, FALSE, 44);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Volunteer Opportunities', 'Community service projects to give back and build skills.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 43);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Family Reunification Services', 'Assistance with reconnecting with family members.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 42);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Transportation Assistance', 'Help with public transportation costs or alternative transportation options.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 41);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Life Skills Training', 'Classes on budgeting, time management, and other essential life skills.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 40);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Support Groups', 'Peer-led groups for individuals with similar experiences.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 39);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Case Management', 'Personalized support and guidance to help individuals navigate the reentry process.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 38);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Victim Services', 'Support for individuals who have been victims of crime.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 37);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Parole Board Preparation', 'Guidance on preparing for parole hearings.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 36);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Expungement Assistance', 'Help with removing criminal records.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 35);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Legal Aid', 'Assistance with civil legal matters (e.g., housing, family law, debt).', NULL, NULL, NULL, FALSE, TRUE, FALSE, 34);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Public Defenders', 'Legal representation in criminal cases.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 33);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('College Admissions Counseling', 'Guidance on applying to colleges and universities.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 32);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Vocational Training', 'Specialized training for specific trades or skills.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 31);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('GED Preparation', 'Classes and resources to help individuals obtain a General Educational Development certificate.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 30);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Resume Building and Interview Preparation', 'Guidance on creating effective resumes and preparing for job interviews.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 29);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Job Placement Services', 'Assistance in finding employment opportunities.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 28);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Job Training', 'Skills development programs for various industries.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 27);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Second Chance Hiring', 'Fast Track to Hire', NULL, NULL, NULL, FALSE, TRUE, FALSE, 26);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Wellness Programs', 'Activities and resources to promote physical and mental health.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 24);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Health Insurance Assistance', 'Help with enrolling in health insurance programs.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 23);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Dental Care', 'Dental services, including cleanings, fillings, and extractions.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 22);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Medical Clinics', 'Primary care services and basic health screenings.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 21);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Substance Abuse Treatment', 'Programs for individuals struggling with addiction.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 20);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Mental Health Counseling', 'Therapy and support for individuals with mental health conditions.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 19);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Cellphone Access', 'Lifeline Setup', NULL, NULL, NULL, FALSE, TRUE, FALSE, 18);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Digital Literacy Skills', 'Education on using technology for job searching, communication, and other essential tasks.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 17);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Internet Access', 'Assistance with obtaining internet access.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 16);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Computer Training', 'Classes on basic computer skills and software applications.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 15);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Digital Literacy', 'Technology Lessons', NULL, NULL, NULL, FALSE, TRUE, FALSE, 14);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Permanent Supportive Housing', 'Affordable housing with ongoing support services for individuals with disabilities or chronic health conditions.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 13);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Transitional Housing', 'Temporary housing with support services to help individuals transition to permanent housing.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 12);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Temporary Shelters', 'Short-term housing for immediate needs.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 11);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Housing and Needs', 'Temporary housing with support services to help individuals transition to permanent housing.', NULL, NULL, NULL, FALSE, TRUE, FALSE, 9);
INSERT INTO public.courses (name, description, course_type, web_link, video_link, in_learning_academy, is_hidden, is_featured, display_order) VALUES ('Ten Reentry Steps', 'Here’s a ten-step guide tailored for individuals in Philadelphia reentering society after incarceration, focusing on securing housing, finding employment, and adjusting to life outside.', 'Basic Needs', NULL, NULL, FALSE, TRUE, FALSE, 1);

-- Course Tasks (12 rows)
INSERT INTO public.course_tasks (name, description, sort_order, course_id) VALUES ('Resume', 'Get information about each job and position I had', 1, (SELECT id FROM public.courses WHERE name = 'How to Write a Great Resume' LIMIT 1));
INSERT INTO public.course_tasks (name, description, sort_order, course_id) VALUES ('Bank Account', 'Find a banking institution that fits my needs', 1.23, (SELECT id FROM public.courses WHERE name = 'Manage a Savings Account' LIMIT 1));
INSERT INTO public.course_tasks (name, description, sort_order, course_id) VALUES ('Step 10: Focus on Self-Care and Adjustment', 'Healthy Routines: Establish daily routines that include exercise, healthy eating, and mindfulness practices.
Community Involvement: Engage with your community through activities, workshops, or local events to foster a sense of belonging.', 10, (SELECT id FROM public.courses WHERE name = 'Ten Reentry Steps' LIMIT 1));
INSERT INTO public.course_tasks (name, description, sort_order, course_id) VALUES ('Step 9: Build a Support Network', 'Reconnect with Family and Friends: Strengthen your support system by reaching out to loved ones.
Support Groups: Join support groups for people reentering society to share experiences and coping strategies.', 9, (SELECT id FROM public.courses WHERE name = 'Ten Reentry Steps' LIMIT 1));
INSERT INTO public.course_tasks (name, description, sort_order, course_id) VALUES ('Step 8: Understand Your Rights', 'Know Your Legal Rights: Familiarize yourself with your rights regarding housing and employment, particularly concerning discrimination due to your criminal record.
Legal Aid Resources: Connect with organizations that provide legal assistance if you face discrimination or challenges.', 8, (SELECT id FROM public.courses WHERE name = 'Ten Reentry Steps' LIMIT 1));
INSERT INTO public.course_tasks (name, description, sort_order, course_id) VALUES ('Step 7: Prepare for Interviews', 'Mock Interviews: Practice interviewing with friends, family, or career coaches to build confidence.
Discuss Your Background: Be prepared to explain your incarceration in a positive light, focusing on what you learned and how you''ve changed.', 7, (SELECT id FROM public.courses WHERE name = 'Ten Reentry Steps' LIMIT 1));
INSERT INTO public.course_tasks (name, description, sort_order, course_id) VALUES ('Step 6: Job Search and Application', 'Resume and Cover Letter: Create a professional resume and cover letter that highlight your skills and experience.
Job Portals and Networking: Use job search websites (like Indeed or LinkedIn) and network through community organizations or job fairs.', 6, (SELECT id FROM public.courses WHERE name = 'Ten Reentry Steps' LIMIT 1));
INSERT INTO public.course_tasks (name, description, sort_order, course_id) VALUES ('Step 5: Develop Job Skills', 'Job Training Programs: Enroll in programs that offer skills training and workshops to enhance your employability.
Volunteer Opportunities: Gain experience and build your resume by volunteering with local nonprofits.', 5, (SELECT id FROM public.courses WHERE name = 'Ten Reentry Steps' LIMIT 1));
INSERT INTO public.course_tasks (name, description, sort_order, course_id) VALUES ('Step 4: Connect with Support Services', 'Reentry Programs: Seek out local organizations that offer support for formerly incarcerated individuals, such as the Philadelphia Reentry Coalition.
Mental Health Services: Consider accessing counseling or mental health services to help with the transition.', 4, (SELECT id FROM public.courses WHERE name = 'Ten Reentry Steps' LIMIT 1));
INSERT INTO public.course_tasks (name, description, sort_order, course_id) VALUES ('Step 3: Find Stable Housing', 'Temporary Housing: Look for shelters or transitional housing programs specifically for those reentering society.
Search for Permanent Housing: Use resources like the Philadelphia Housing Authority or local housing agencies. Check for any programs that assist individuals with criminal records.', 3, (SELECT id FROM public.courses WHERE name = 'Ten Reentry Steps' LIMIT 1));
INSERT INTO public.course_tasks (name, description, sort_order, course_id) VALUES ('Step 2: Secure Identification', 'Obtain Necessary IDs: Ensure you have a government-issued ID, Social Security card, and any necessary documents that can aid in employment and housing applications.
Contact Local Organizations: Organizations like the Philadelphia Office of Reentry Partnerships can help with obtaining these documents.', 2, (SELECT id FROM public.courses WHERE name = 'Ten Reentry Steps' LIMIT 1));
INSERT INTO public.course_tasks (name, description, sort_order, course_id) VALUES ('Step 1: Create a Reentry Plan', 'Assess Your Needs: Outline your immediate needs for housing, employment, and support.
Set Goals: Identify short-term and long-term goals, such as finding a job within three months or stable housing within six.', 1, (SELECT id FROM public.courses WHERE name = 'Ten Reentry Steps' LIMIT 1));

-- Questions (7 rows)
INSERT INTO public.questions (question, category, upvotes, is_faq, asked_by) VALUES ('How do I download documents?', NULL, 9, TRUE, 'colleennguyn@hotmail.edu');
INSERT INTO public.questions (question, category, upvotes, is_faq, asked_by) VALUES ('How long can I access an event?', NULL, 4, TRUE, 'andrewrichardson59@example.com');
INSERT INTO public.questions (question, category, upvotes, is_faq, asked_by) VALUES ('How do I reset my password?', NULL, 6, TRUE, 'carlyherrera8150@yahoo.ca');
INSERT INTO public.questions (question, category, upvotes, is_faq, asked_by) VALUES ('How do I login to my FreePass?', NULL, 11, TRUE, 'nellhe@hotmail.edu');
INSERT INTO public.questions (question, category, upvotes, is_faq, asked_by) VALUES ('What platforms are supported by the FreePass app?', NULL, 9, TRUE, 'anjolieschippers1129@hotmail.ca');
INSERT INTO public.questions (question, category, upvotes, is_faq, asked_by) VALUES ('How can I get money to help with renting a house', 'Housing', 7, FALSE, 'projectfree83@gmail.com');
INSERT INTO public.questions (question, category, upvotes, is_faq, asked_by) VALUES ('What should I get ready for my housing search?', 'Housing', 9, FALSE, 'macy3297@yahoo.net');

-- Answers (4 rows, excluding test entries)
INSERT INTO public.answers (answer, question_id, answered_by, upvotes) VALUES ('You can access the event whenever you want. Just click past event on the events page and you will see everything', (SELECT id FROM public.questions WHERE question = 'How long can I access an event?' LIMIT 1), 'projectfree83@gmail.com', NULL);
INSERT INTO public.answers (answer, question_id, answered_by, upvotes) VALUES ('Google Chrome
Smart Phones', (SELECT id FROM public.questions WHERE question = 'What platforms are supported by the FreePass app?' LIMIT 1), 'projectfree83@gmail.com', NULL);
INSERT INTO public.answers (answer, question_id, answered_by, upvotes) VALUES ('The Fountain Fund.
Go to the website and fill out an inquiry.

www.fountainfund.org', (SELECT id FROM public.questions WHERE question = 'How can I get money to help with renting a house' LIMIT 1), 'projectfree83@gmail.com', 1);
INSERT INTO public.answers (answer, question_id, answered_by, upvotes) VALUES ('Read up on Chapter 2 of the FreePass guidebook. Also consider reaching out to Project HOME, their info is included within FreePass.', (SELECT id FROM public.questions WHERE question = 'What should I get ready for my housing search?' LIMIT 1), 'danderosato@gmail.com', 1);

-- Drop old Adalo-imported uppercase tables (data now in lowercase tables)
DROP TABLE IF EXISTS public."Courses" CASCADE;
DROP TABLE IF EXISTS public."Events" CASCADE;
DROP TABLE IF EXISTS public."Resources" CASCADE;

-- Verification counts
SELECT 'resource_categories' AS tbl, count(*) FROM public.resource_categories
UNION ALL
SELECT 'resources', count(*) FROM public.resources
UNION ALL
SELECT 'events', count(*) FROM public.events
UNION ALL
SELECT 'courses', count(*) FROM public.courses
UNION ALL
SELECT 'course_tasks', count(*) FROM public.course_tasks
UNION ALL
SELECT 'questions', count(*) FROM public.questions
UNION ALL
SELECT 'answers', count(*) FROM public.answers;

COMMIT;
